services:
  product:
    build:
      context: .
    env_file:
      - .env.test
    environment:
      NODE_ENV: test
      MONGO_URI: mongodb://product-mongodb:27017/
      REDIS_URL: redis://redis:6379
    command: npm test
    depends_on:
      - product-mongodb

  product-mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      MONGO_INITDB_DATABASE: test_db
    volumes:
      - productTestDB:/data/db

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - productTestCache:/root/redis

volumes:
  productTestDB:
  productTestCache:
